### ISSUE TITLE
Moving CI to Github Actions - Roadmap

### ISSUE THREAD

**Issue by JoaoRodrigues** [biopython/biopython#3688]
This issue will track what has been done to move our CI workflow to Github Actions, as well as possible ideas/enhancements.

- [x] Style checking using pre-commit.
- [x] Building steps (dist and wheel).
- [x] Offline tests (base dependencies).
- [x] Testing on PyPy (only on Linux)
- [x] Get test coverage.
- [x] Building Documentation with Sphinx (partially done, see below)

- [ ] Check RST files: implemented but not working (syntax error, see [here](https://github.com/biopython/biopython/pull/3681#issuecomment-890686139)).
- [ ] Upload coverage data to CodeCov
- [ ] Build the API docs with Sphinx and push that to GitHub Pages (was on TravisCI, now on CircleCI as of #3678)
- [ ] Non-Python dependency testing (e.g. ``paml`` - had lots on TravisCI, will be less as we remove application wrappers - see #3344)

Wishlist:
- [ ] Automatic deployment to conda/PyPI of development / tagged versions / releases (see https://github.com/pypa/cibuildwheel)

**Comment by peterjc** [comment]
For the wish list of deployment of wheels, that is currently done on https://github.com/biopython/biopython-wheels - cross reference https://github.com/matthew-brett/multibuild/issues/416

**Comment by erik-whiting** [comment]
@JoaoRodrigues / @peterjc do you mind if I take a shot at building the API docs that push to GitHub pages? I see some references to Travis in the `deploy_docs.sh` file so I assume there's still work to be done. If not, no big deal, but I think I can figure it out after a while in my own fork (I hope).

**Comment by peterjc** [comment]
Sure. I had tried calling ``deploy_docs.sh`` from the deploy stage https://github.com/biopython/biopython/blob/master/.circleci/config.yml but it wasn't working, thus 4d8b7593be67e5361bd908d810709058037e7a4f

You'll likely need to do this all on your own fork, pushing the documentation to a fork of the documentation repository (where you can give write access via a key or otherwise).

**Comment by erik-whiting** [comment]
Sphinx deployment PR is ready for a look here: https://github.com/erik-whiting/biopython/pull/1
